# Site settings
title: Becca Aaronson
email: becca.aaronson@gmail.com
description: "This is the story of a girl who loved cats."
baseurl: ""
url: "http://brickaa.github.io"
insta_username: hello_becca
twitter_username: becca_aa
github_username:  brickaa

# Build settings
markdown: kramdown
permalink: pretty
masonry_js: masonry.min.js


#
# Jekyll-Assets configuration
#

assets:
  compress:
    css: sass