# Site settings
title: Becca Aaronson
email: becca.aaronson@gmail.com.com
description: "This is the story of a girl who loved cats."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: becca_aa
github_username:  brickaa

# Build settings
markdown: kramdown
permalink: pretty
